
#line 3 "lex.Int_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define Int_yyconst const
#else
#define Int_yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (Int_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((Int_yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Int_yyrestart(Int_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(Int_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct Int_yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int Int_yyleng;

extern FILE *Int_yyin, *Int_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define Int_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Int_yytext. */ \
        int Int_yyless_macro_arg = (n); \
        YY_LESS_LINENO(Int_yyless_macro_arg);\
		*Int_yy_cp = (Int_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(Int_yy_c_buf_p) = Int_yy_cp = Int_yy_bp + Int_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Int_yytext again */ \
		} \
	while ( 0 )

#define unput(c) Int_yyunput( c, (Int_yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t Int_yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct Int_yy_buffer_state
	{
	FILE *Int_yy_input_file;

	char *Int_yy_ch_buf;		/* input buffer */
	char *Int_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	Int_yy_size_t Int_yy_buf_size;

	/* Number of characters read into Int_yy_ch_buf, not including EOB
	 * characters.
	 */
	int Int_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int Int_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int Int_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int Int_yy_at_bol;

    int Int_yy_bs_lineno; /**< The line count. */
    int Int_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int Int_yy_fill_buffer;

	int Int_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Int_yyrestart()), so that the user can continue scanning by
	 * just pointing Int_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t Int_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t Int_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * Int_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (Int_yy_buffer_stack) \
                          ? (Int_yy_buffer_stack)[(Int_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (Int_yy_buffer_stack)[(Int_yy_buffer_stack_top)]

/* Int_yy_hold_char holds the character lost when Int_yytext is formed. */
static char Int_yy_hold_char;
static int Int_yy_n_chars;		/* number of characters read into Int_yy_ch_buf */
int Int_yyleng;

/* Points to current character in buffer. */
static char *Int_yy_c_buf_p = (char *) 0;
static int Int_yy_init = 0;		/* whether we need to initialize */
static int Int_yy_start = 0;	/* start state number */

/* Flag which is used to allow Int_yywrap()'s to do buffer switches
 * instead of setting up a fresh Int_yyin.  A bit of a hack ...
 */
static int Int_yy_did_buffer_switch_on_eof;

void Int_yyrestart (FILE *input_file  );
void Int_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Int_yy_create_buffer (FILE *file,int size  );
void Int_yy_delete_buffer (YY_BUFFER_STATE b  );
void Int_yy_flush_buffer (YY_BUFFER_STATE b  );
void Int_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void Int_yypop_buffer_state (void );

static void Int_yyensure_buffer_stack (void );
static void Int_yy_load_buffer_state (void );
static void Int_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER Int_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE Int_yy_scan_buffer (char *base,Int_yy_size_t size  );
YY_BUFFER_STATE Int_yy_scan_string (Int_yyconst char *Int_yy_str  );
YY_BUFFER_STATE Int_yy_scan_bytes (Int_yyconst char *bytes,int len  );

void *Int_yyalloc (Int_yy_size_t  );
void *Int_yyrealloc (void *,Int_yy_size_t  );
void Int_yyfree (void *  );

#define Int_yy_new_buffer Int_yy_create_buffer

#define Int_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Int_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Int_yy_create_buffer(Int_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->Int_yy_is_interactive = is_interactive; \
	}

#define Int_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Int_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Int_yy_create_buffer(Int_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *Int_yyin = (FILE *) 0, *Int_yyout = (FILE *) 0;

typedef int Int_yy_state_type;

extern int Int_yylineno;

int Int_yylineno = 1;

extern char *Int_yytext;
#define Int_yytext_ptr Int_yytext

static Int_yy_state_type Int_yy_get_previous_state (void );
static Int_yy_state_type Int_yy_try_NUL_trans (Int_yy_state_type current_state  );
static int Int_yy_get_next_buffer (void );
static void Int_yy_fatal_error (Int_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Int_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(Int_yytext_ptr) = Int_yy_bp; \
	Int_yyleng = (size_t) (Int_yy_cp - Int_yy_bp); \
	(Int_yy_hold_char) = *Int_yy_cp; \
	*Int_yy_cp = '\0'; \
	(Int_yy_c_buf_p) = Int_yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct Int_yy_trans_info
	{
	flex_int32_t Int_yy_verify;
	flex_int32_t Int_yy_nxt;
	};
static Int_yyconst flex_int16_t Int_yy_accept[135] =
    {   0,
        0,    0,   31,   29,   13,   12,   14,   29,   10,   11,
        8,   24,   29,   24,    9,   24,   24,   29,   24,   24,
       24,   24,   24,   24,   24,   15,    0,   25,   24,    0,
       24,    0,   27,   26,   24,   24,   24,    0,   24,   24,
        0,   24,   24,   24,   24,   24,   24,   24,   21,   24,
       24,   24,   15,   24,   24,   27,    0,   26,   26,    0,
        0,   24,   24,   24,    0,   23,   24,    4,    0,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    0,   27,   27,   27,   26,    0,    0,
       26,   26,   26,   28,   24,   24,   24,   24,   24,   24,

       24,   24,   24,    1,   24,   24,    0,   26,   26,   26,
       24,   24,   17,    2,   24,   24,   20,   24,   24,   24,
       22,    6,   24,    3,   24,   24,    7,   19,   24,   16,
       18,   24,    5,    0
    } ;

static Int_yyconst flex_int32_t Int_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    1,    9,   10,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
       14,    1,    1,    1,   13,   13,   13,   15,   16,   13,
       17,   17,   18,   17,   17,   17,   17,   17,   19,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       20,   21,   22,    1,   23,    1,   24,   25,   26,   27,

       28,   17,   29,   17,   30,   17,   17,   31,   17,   32,
       33,   34,   35,   36,   37,   38,   39,   17,   17,   40,
       17,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static Int_yyconst flex_int32_t Int_yy_meta[41] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    1,    3,    3,    3,    3,    3,    4,
        3,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static Int_yyconst flex_int16_t Int_yy_base[139] =
    {   0,
        0,   74,   79,  475,  475,  475,  475,   71,  475,  475,
      475,   29,   33,   40,  475,   46,   51,   19,   53,   66,
       57,   42,   50,   68,   71,    0,   49,  475,   85,   79,
       99,    7,  103,  108,  125,  117,   96,  129,  156,  110,
      139,  117,  124,  129,  127,  142,  147,  151,  143,  146,
      161,  163,    0,  188,  196,  204,  212,  218,  226,  234,
      240,  137,  244,  252,  256,  475,  205,  144,  260,  205,
      241,  231,  244,  258,  253,  257,  159,  219,  260,  268,
      289,  297,  300,  301,  305,    0,  309,  319,  327,  333,
      337,    0,  341,  345,  298,  329,  312,  331,  334,  345,

      341,  349,  350,  255,  338,  358,  377,  383,    0,  387,
      362,  371,  373,  374,  386,  382,  383,  395,  391,  398,
      394,  399,  403,  402,  412,  410,  411,  413,  424,  420,
      421,  422,  425,  475,  464,   40,  466,  470
    } ;

static Int_yyconst flex_int16_t Int_yy_def[139] =
    {   0,
      134,    1,  134,  134,  134,  134,  134,  135,  134,  134,
      134,  136,  134,  137,  134,  137,  137,  134,  137,  137,
       20,   20,   20,   20,   20,  138,  135,  134,  136,  134,
      136,  134,  134,  134,   20,   35,   20,  134,   20,   20,
      134,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,  138,   31,   31,  134,  134,  134,  134,  134,
      134,   55,   35,   35,  134,  134,   39,   20,  134,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       31,   31,   55,  134,  134,   56,  134,  134,  134,  134,
      134,   88,  134,  134,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,  134,  134,   88,  134,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,    0,  134,  134,  134,  134
    } ;

static Int_yyconst flex_int16_t Int_yy_nxt[516] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,    4,   11,
       12,   13,   14,   15,   14,   14,   16,   16,   17,    4,
       18,    4,   19,   16,   20,   21,   22,   16,   16,   23,
       16,   16,   24,   16,   16,   16,   16,   16,   25,   16,
       30,   31,   29,   31,   31,   33,   41,   33,   33,   32,
       29,   34,   35,   28,   35,   36,   29,  134,   41,   38,
       32,   29,  134,   29,  134,   38,   32,   39,   40,   47,
       38,   32,   38,   32,   37,   28,   29,  134,  134,   26,
       37,   48,   37,  134,   42,   38,   32,   45,   37,   37,
      134,   33,   46,   33,   33,   37,  134,  134,   43,   49,

       37,   50,   51,   37,   44,   32,   37,   52,  134,   37,
       34,   31,  134,   31,   54,   33,  134,   33,   56,   32,
       58,  134,   58,   59,   68,   61,   55,   62,   37,   63,
       57,   63,   64,  134,   37,   60,   34,   35,  134,   35,
       36,   65,   37,   65,   65,  134,  134,   29,   37,   37,
       66,   69,   39,   69,   69,   70,   71,   37,   72,   73,
      134,   37,   37,   37,   61,   37,   62,   37,   67,   74,
       67,   67,   75,   78,   37,   37,   37,   76,   37,   37,
       37,   37,   37,   37,   37,   37,  103,   77,   37,   37,
       79,   37,   80,   37,   37,   37,   61,   37,   62,   37,

       81,   37,   81,   82,   61,  134,   62,  134,   83,  134,
       83,   83,   84,  134,   84,   29,   85,  134,   85,   86,
       84,  134,   84,   29,   87,  134,   87,   87,  134,  134,
       58,   57,   58,   88,   90,   95,   90,   37,   91,  134,
       91,   92,   90,   37,   90,   89,   93,  134,   93,   93,
      104,   37,   94,   89,   94,   94,   63,   37,   63,   64,
       61,   97,   62,   37,   63,  134,   63,   64,   65,   37,
       65,   65,   29,   37,   29,   29,   37,   66,   96,   37,
       98,   99,   37,  100,  101,   37,  102,   37,  134,   37,
       37,   37,   37,   37,  105,   37,   37,  134,   37,  106,

       37,   81,  134,   81,   82,   61,   37,   62,  134,   81,
       29,   81,   82,   87,  134,   87,   87,   85,  134,   85,
       86,   87,  134,   87,   87,  134,  134,  107,  111,  107,
       37,  108,   57,  108,  109,  107,   37,  107,  113,  110,
      134,  110,  110,  134,   37,   93,   89,   93,   93,   91,
       37,   91,   92,   93,  134,   93,   93,   94,  114,   94,
       94,   37,  134,   37,   89,  112,   37,   37,  116,   37,
       37,  115,   37,   37,  118,  134,  120,   37,  134,   37,
      117,   37,   37,   37,  122,  119,  121,   37,   37,  110,
       37,  110,  110,  134,   37,  108,   37,  108,  109,  110,

       37,  110,  110,   37,  134,   37,   37,  134,  123,   37,
       89,   37,   37,  124,   37,   37,  134,  125,   37,  134,
       37,   37,  126,   37,   37,  128,   37,   37,  127,   37,
       37,   37,   37,   37,   37,   37,   37,   37,  129,  130,
       37,   37,   37,   37,   37,   37,  131,  132,   37,   37,
       37,   37,   37,   37,   37,  133,   37,   37,   37,   37,
       37,  134,   37,   37,   27,   27,   27,   27,   37,   37,
       53,  134,   53,   53,    3,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134
    } ;

static Int_yyconst flex_int16_t Int_yy_chk[516] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       12,   12,  136,   12,   12,   13,   32,   13,   13,   12,
       14,   14,   14,   27,   14,   14,   16,   16,   18,   14,
       14,   17,   17,   19,   19,   16,   16,   14,   17,   22,
       17,   17,   19,   19,   22,    8,   20,   20,    3,    2,
       22,   23,   23,    0,   19,   20,   20,   21,   23,   21,
        0,   30,   21,   30,   30,   21,   29,    0,   20,   24,

       24,   24,   25,   25,   20,   29,   24,   25,    0,   25,
       31,   31,    0,   31,   31,   33,    0,   33,   33,   31,
       34,    0,   34,   34,   40,   36,   31,   36,   37,   36,
       33,   36,   36,    0,   37,   34,   35,   35,    0,   35,
       35,   38,   40,   38,   38,   62,    0,   62,   40,   42,
       38,   41,   35,   41,   41,   42,   43,   35,   44,   45,
        0,   44,   43,   35,   39,   45,   39,   44,   39,   46,
       39,   39,   47,   50,   46,   49,   68,   48,   50,   47,
       46,   49,   68,   48,   50,   47,   77,   48,   39,   48,
       51,   77,   52,   51,   39,   52,   54,   77,   54,   51,

       54,   52,   54,   54,   55,    0,   55,   55,   55,    0,
       55,   55,   56,   67,   56,   67,   56,    0,   56,   56,
       57,    0,   57,   55,   57,    0,   57,   57,    0,    0,
       58,   56,   58,   58,   59,   70,   59,   70,   59,    0,
       59,   59,   60,   70,   60,   58,   60,    0,   60,   60,
       78,   78,   61,   59,   61,   61,   63,   78,   63,   63,
       64,   72,   64,   72,   64,    0,   64,   64,   65,   72,
       65,   65,   69,   71,   69,   69,   73,   65,   71,   71,
       73,   74,   73,   75,   76,   75,   76,  104,    0,   76,
       74,   75,   79,  104,   79,   76,   74,    0,   79,   80,

       80,   81,    0,   81,   81,   82,   80,   82,   83,   82,
       83,   82,   82,   84,    0,   84,   84,   85,    0,   85,
       85,   87,    0,   87,   87,    0,    0,   88,   95,   88,
       95,   88,   85,   88,   88,   89,   95,   89,   97,   89,
        0,   89,   89,    0,   97,   90,   88,   90,   90,   91,
       97,   91,   91,   93,    0,   93,   93,   94,   98,   94,
       94,   96,    0,   98,   91,   96,   99,   96,  100,   98,
      105,   99,   99,  101,  102,    0,  105,  100,    0,  101,
      101,  102,  103,  100,  111,  103,  106,  102,  103,  107,
      106,  107,  107,    0,  111,  108,  106,  108,  108,  110,

      111,  110,  110,  112,    0,  113,  114,    0,  112,  112,
      108,  113,  114,  115,  116,  117,    0,  116,  115,    0,
      116,  117,  118,  119,  115,  120,  121,  118,  119,  119,
      120,  122,  121,  118,  124,  123,  120,  122,  123,  125,
      124,  123,  126,  127,  125,  128,  126,  129,  126,  127,
      125,  128,  130,  131,  132,  132,  129,  133,  130,  131,
      132,    0,  129,  133,  135,  135,  135,  135,  137,  137,
      138,    0,  138,  138,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134
    } ;

static Int_yy_state_type Int_yy_last_accepting_state;
static char *Int_yy_last_accepting_cpos;

extern int Int_yy_flex_debug;
int Int_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define Int_yymore() Int_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Int_yytext;
#line 1 "bootscanner.l"
#line 2 "bootscanner.l"
/*-------------------------------------------------------------------------
 *
 * bootscanner.lex
 *	  a lexical scanner for the bootstrap parser
 *
 * Portions Copyright (c) 1996-2000, PostgreSQL, Inc
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 *
 * IDENTIFICATION
 *	  $Header: /cvs/weaver/mtpgsql/src/backend/bootstrap/bootscanner.l,v 1.1.1.1 2006/08/12 00:20:07 synmscott Exp $
 *
 *-------------------------------------------------------------------------
 */
#include <time.h>

#include "postgres.h"
#include "env/env.h"

#include "access/attnum.h"
#include "access/funcindex.h"
#include "access/htup.h"
#include "access/itup.h"
#include "access/skey.h"
#include "access/strat.h"
#include "access/tupdesc.h"
#include "bootstrap/bootstrap.h"
#include "catalog/pg_am.h"
#include "catalog/pg_attribute.h"
#include "catalog/pg_class.h"
#include "nodes/nodes.h"
#include "nodes/parsenodes.h"
#include "nodes/pg_list.h"
#include "nodes/primnodes.h"
#include "parser/parserinfo.h"
#include "parser/scansup.h"
#include "rewrite/prs2lock.h"
#include "storage/block.h"
#include "storage/fd.h"
#include "storage/itemptr.h"
#include "storage/off.h"
#include "utils/nabstime.h"
#include "utils/rel.h"

#include "bootstrap_tokens.h"

#define			YY_NO_UNPUT

#define YY_DECL int Int_yylex(sval) YYSTYPE* sval;

/* some versions of lex define this as a macro */
#if defined(Int_yywrap)
#undef Int_yywrap
#endif /* Int_yywrap */

/* YYSTYPE Int_yylval;  */
/*  int		GetParserInfo()->Int_yyline;  *//* keep track of the line number for error reporting */

#line 665 "lex.Int_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int Int_yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Int_yylex_destroy (void );

int Int_yyget_debug (void );

void Int_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE Int_yyget_extra (void );

void Int_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *Int_yyget_in (void );

void Int_yyset_in  (FILE * in_str  );

FILE *Int_yyget_out (void );

void Int_yyset_out  (FILE * out_str  );

int Int_yyget_leng (void );

char *Int_yyget_text (void );

int Int_yyget_lineno (void );

void Int_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Int_yywrap (void );
#else
extern int Int_yywrap (void );
#endif
#endif

    static void Int_yyunput (int c,char *buf_ptr  );
    
#ifndef Int_yytext_ptr
static void Int_yy_flex_strncpy (char *,Int_yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int Int_yy_flex_strlen (Int_yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int Int_yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( Int_yytext, Int_yyleng, 1, Int_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Int_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Int_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, Int_yyin))==0 && ferror(Int_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Int_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "Int_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef Int_yyterminate
#define Int_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) Int_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Int_yylex (void);

#define YY_DECL int Int_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Int_yytext and Int_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( Int_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol = \
				(Int_yytext[Int_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register Int_yy_state_type Int_yy_current_state;
	register char *Int_yy_cp, *Int_yy_bp;
	register int Int_yy_act;
    
#line 69 "bootscanner.l"


#line 853 "lex.Int_yy.c"

	if ( !(Int_yy_init) )
		{
		(Int_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (Int_yy_start) )
			(Int_yy_start) = 1;	/* first start state */

		if ( ! Int_yyin )
			Int_yyin = stdin;

		if ( ! Int_yyout )
			Int_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Int_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Int_yy_create_buffer(Int_yyin,YY_BUF_SIZE );
		}

		Int_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		Int_yy_cp = (Int_yy_c_buf_p);

		/* Support of Int_yytext. */
		*Int_yy_cp = (Int_yy_hold_char);

		/* Int_yy_bp points to the position in Int_yy_ch_buf of the start of
		 * the current run.
		 */
		Int_yy_bp = Int_yy_cp;

		Int_yy_current_state = (Int_yy_start);
		Int_yy_current_state += YY_AT_BOL();
Int_yy_match:
		do
			{
			register YY_CHAR Int_yy_c = Int_yy_ec[YY_SC_TO_UI(*Int_yy_cp)];
			if ( Int_yy_accept[Int_yy_current_state] )
				{
				(Int_yy_last_accepting_state) = Int_yy_current_state;
				(Int_yy_last_accepting_cpos) = Int_yy_cp;
				}
			while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state )
				{
				Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
				if ( Int_yy_current_state >= 135 )
					Int_yy_c = Int_yy_meta[(unsigned int) Int_yy_c];
				}
			Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + (unsigned int) Int_yy_c];
			++Int_yy_cp;
			}
		while ( Int_yy_base[Int_yy_current_state] != 475 );

Int_yy_find_action:
		Int_yy_act = Int_yy_accept[Int_yy_current_state];
		if ( Int_yy_act == 0 )
			{ /* have to back up */
			Int_yy_cp = (Int_yy_last_accepting_cpos);
			Int_yy_current_state = (Int_yy_last_accepting_state);
			Int_yy_act = Int_yy_accept[Int_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( Int_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*Int_yy_cp = (Int_yy_hold_char);
			Int_yy_cp = (Int_yy_last_accepting_cpos);
			Int_yy_current_state = (Int_yy_last_accepting_state);
			goto Int_yy_find_action;

case 1:
YY_RULE_SETUP
#line 71 "bootscanner.l"
{ return(OPEN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "bootscanner.l"
{ return(XCLOSE); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "bootscanner.l"
{ return(XCREATE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 77 "bootscanner.l"
{ return(OBJ_ID); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "bootscanner.l"
{ return(XBOOTSTRAP); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "bootscanner.l"
{ return(NULLVAL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "bootscanner.l"
{ return(INSERT_TUPLE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "bootscanner.l"
{ return(COMMA); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "bootscanner.l"
{ return(EQUALS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "bootscanner.l"
{ return(LPAREN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "bootscanner.l"
{ return(RPAREN); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 88 "bootscanner.l"
{ GetParserInfo()->Int_yyline++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "bootscanner.l"
;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 "bootscanner.l"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "bootscanner.l"
; /* drop everything after "#" for comments */
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "bootscanner.l"
{ return(XDECLARE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "bootscanner.l"
{ return(XBUILD); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "bootscanner.l"
{ return(INDICES); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "bootscanner.l"
{ return(UNIQUE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "bootscanner.l"
{ return(INDEX); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "bootscanner.l"
{ return(ON); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "bootscanner.l"
{ return(USING); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "bootscanner.l"
{
					sval->ival = EnterString(MapArrayTypeName((char*)GetParserInfo()->Int_yytext));
					return(ID);
				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 106 "bootscanner.l"
{
                    ParserInfo*  pinfo = GetParserInfo();
					char   *newid = scanstr((char*)pinfo->Int_yytext);
					sval->ival = EnterString(newid);
					pfree(newid);
					return(ID);
				}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 113 "bootscanner.l"
{
					char   *newid;
                    ParserInfo*  pinfo = GetParserInfo();
					pinfo->Int_yytext[strlen(pinfo->Int_yytext)-1] = '\0'; /* strip off quotes */
					newid = scanstr((char*)pinfo->Int_yytext+1);
					sval->ival = EnterString(newid);
					pfree(newid);
					pinfo->Int_yytext[strlen(pinfo->Int_yytext)] = '"'; /* restore quotes */
					return(ID);
				}
	YY_BREAK
case 26:
#line 125 "bootscanner.l"
case 27:
#line 126 "bootscanner.l"
case 28:
YY_RULE_SETUP
#line 126 "bootscanner.l"
{
							sval->ival = EnterString((char*)GetParserInfo()->Int_yytext);
							return(CONST);
						}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "bootscanner.l"
{
					printf("syntax error %d : -> %s\n", GetParserInfo()->Int_yyline, GetParserInfo()->Int_yytext);
				}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "bootscanner.l"
ECHO;
	YY_BREAK
#line 1106 "lex.Int_yy.c"
case YY_STATE_EOF(INITIAL):
	Int_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int Int_yy_amount_of_matched_text = (int) (Int_yy_cp - (Int_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*Int_yy_cp = (Int_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Int_yyin at a new source and called
			 * Int_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(Int_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->Int_yy_input_file = Int_yyin;
			YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for Int_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since Int_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (Int_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)] )
			{ /* This was really a NUL. */
			Int_yy_state_type Int_yy_next_state;

			(Int_yy_c_buf_p) = (Int_yytext_ptr) + Int_yy_amount_of_matched_text;

			Int_yy_current_state = Int_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * Int_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			Int_yy_next_state = Int_yy_try_NUL_trans( Int_yy_current_state );

			Int_yy_bp = (Int_yytext_ptr) + YY_MORE_ADJ;

			if ( Int_yy_next_state )
				{
				/* Consume the NUL. */
				Int_yy_cp = ++(Int_yy_c_buf_p);
				Int_yy_current_state = Int_yy_next_state;
				goto Int_yy_match;
				}

			else
				{
				Int_yy_cp = (Int_yy_c_buf_p);
				goto Int_yy_find_action;
				}
			}

		else switch ( Int_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(Int_yy_did_buffer_switch_on_eof) = 0;

				if ( Int_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * Int_yy_get_next_buffer() to have set up
					 * Int_yytext, we can now set up
					 * Int_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(Int_yy_c_buf_p) = (Int_yytext_ptr) + YY_MORE_ADJ;

					Int_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (Int_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(Int_yy_c_buf_p) =
					(Int_yytext_ptr) + Int_yy_amount_of_matched_text;

				Int_yy_current_state = Int_yy_get_previous_state(  );

				Int_yy_cp = (Int_yy_c_buf_p);
				Int_yy_bp = (Int_yytext_ptr) + YY_MORE_ADJ;
				goto Int_yy_match;

			case EOB_ACT_LAST_MATCH:
				(Int_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)];

				Int_yy_current_state = Int_yy_get_previous_state(  );

				Int_yy_cp = (Int_yy_c_buf_p);
				Int_yy_bp = (Int_yytext_ptr) + YY_MORE_ADJ;
				goto Int_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of Int_yylex */

/* Int_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int Int_yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf;
	register char *source = (Int_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (Int_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (Int_yy_c_buf_p) - (Int_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((Int_yy_c_buf_p) - (Int_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int Int_yy_c_buf_p_offset =
				(int) ((Int_yy_c_buf_p) - b->Int_yy_ch_buf);

			if ( b->Int_yy_is_our_buffer )
				{
				int new_size = b->Int_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->Int_yy_buf_size += b->Int_yy_buf_size / 8;
				else
					b->Int_yy_buf_size *= 2;

				b->Int_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Int_yyrealloc((void *) b->Int_yy_ch_buf,b->Int_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->Int_yy_ch_buf = 0;

			if ( ! b->Int_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(Int_yy_c_buf_p) = &b->Int_yy_ch_buf[Int_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[number_to_move]),
			(Int_yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars);
		}

	if ( (Int_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Int_yyrestart(Int_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((Int_yy_size_t) ((Int_yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		Int_yy_size_t new_size = (Int_yy_n_chars) + number_to_move + ((Int_yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf = (char *) Int_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in Int_yy_get_next_buffer()" );
	}

	(Int_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(Int_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[0];

	return ret_val;
}

/* Int_yy_get_previous_state - get the state just before the EOB char was reached */

    static Int_yy_state_type Int_yy_get_previous_state (void)
{
	register Int_yy_state_type Int_yy_current_state;
	register char *Int_yy_cp;
    
	Int_yy_current_state = (Int_yy_start);
	Int_yy_current_state += YY_AT_BOL();

	for ( Int_yy_cp = (Int_yytext_ptr) + YY_MORE_ADJ; Int_yy_cp < (Int_yy_c_buf_p); ++Int_yy_cp )
		{
		register YY_CHAR Int_yy_c = (*Int_yy_cp ? Int_yy_ec[YY_SC_TO_UI(*Int_yy_cp)] : 1);
		if ( Int_yy_accept[Int_yy_current_state] )
			{
			(Int_yy_last_accepting_state) = Int_yy_current_state;
			(Int_yy_last_accepting_cpos) = Int_yy_cp;
			}
		while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state )
			{
			Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
			if ( Int_yy_current_state >= 135 )
				Int_yy_c = Int_yy_meta[(unsigned int) Int_yy_c];
			}
		Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + (unsigned int) Int_yy_c];
		}

	return Int_yy_current_state;
}

/* Int_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = Int_yy_try_NUL_trans( current_state );
 */
    static Int_yy_state_type Int_yy_try_NUL_trans  (Int_yy_state_type Int_yy_current_state )
{
	register int Int_yy_is_jam;
    	register char *Int_yy_cp = (Int_yy_c_buf_p);

	register YY_CHAR Int_yy_c = 1;
	if ( Int_yy_accept[Int_yy_current_state] )
		{
		(Int_yy_last_accepting_state) = Int_yy_current_state;
		(Int_yy_last_accepting_cpos) = Int_yy_cp;
		}
	while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state )
		{
		Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
		if ( Int_yy_current_state >= 135 )
			Int_yy_c = Int_yy_meta[(unsigned int) Int_yy_c];
		}
	Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + (unsigned int) Int_yy_c];
	Int_yy_is_jam = (Int_yy_current_state == 134);

	return Int_yy_is_jam ? 0 : Int_yy_current_state;
}

    static void Int_yyunput (int c, register char * Int_yy_bp )
{
	register char *Int_yy_cp;
    
    Int_yy_cp = (Int_yy_c_buf_p);

	/* undo effects of setting up Int_yytext */
	*Int_yy_cp = (Int_yy_hold_char);

	if ( Int_yy_cp < YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (Int_yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf )
			*--dest = *--source;

		Int_yy_cp += (int) (dest - source);
		Int_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars =
			(Int_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size;

		if ( Int_yy_cp < YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--Int_yy_cp = (char) c;

	(Int_yytext_ptr) = Int_yy_bp;
	(Int_yy_hold_char) = *Int_yy_cp;
	(Int_yy_c_buf_p) = Int_yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int Int_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(Int_yy_c_buf_p) = (Int_yy_hold_char);

	if ( *(Int_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* Int_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (Int_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)] )
			/* This was really a NUL. */
			*(Int_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (Int_yy_c_buf_p) - (Int_yytext_ptr);
			++(Int_yy_c_buf_p);

			switch ( Int_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because Int_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Int_yyrestart(Int_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Int_yywrap( ) )
						return EOF;

					if ( ! (Int_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return Int_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(Int_yy_c_buf_p) = (Int_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (Int_yy_c_buf_p);	/* cast for 8-bit char's */
	*(Int_yy_c_buf_p) = '\0';	/* preserve Int_yytext */
	(Int_yy_hold_char) = *++(Int_yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Int_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Int_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Int_yy_create_buffer(Int_yyin,YY_BUF_SIZE );
	}

	Int_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	Int_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Int_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Int_yypop_buffer_state();
	 *		Int_yypush_buffer_state(new_buffer);
     */
	Int_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(Int_yy_c_buf_p) = (Int_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_pos = (Int_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Int_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (Int_yywrap()) processing, but the only time this flag
	 * is looked at is after Int_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(Int_yy_did_buffer_switch_on_eof) = 1;
}

static void Int_yy_load_buffer_state  (void)
{
    	(Int_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars;
	(Int_yytext_ptr) = (Int_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_pos;
	Int_yyin = YY_CURRENT_BUFFER_LVALUE->Int_yy_input_file;
	(Int_yy_hold_char) = *(Int_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Int_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Int_yyalloc(sizeof( struct Int_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_create_buffer()" );

	b->Int_yy_buf_size = size;

	/* Int_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->Int_yy_ch_buf = (char *) Int_yyalloc(b->Int_yy_buf_size + 2  );
	if ( ! b->Int_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_create_buffer()" );

	b->Int_yy_is_our_buffer = 1;

	Int_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Int_yy_create_buffer()
 * 
 */
    void Int_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->Int_yy_is_our_buffer )
		Int_yyfree((void *) b->Int_yy_ch_buf  );

	Int_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Int_yyrestart() or at EOF.
 */
    static void Int_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Int_yy_flush_buffer(b );

	b->Int_yy_input_file = file;
	b->Int_yy_fill_buffer = 1;

    /* If b is the current buffer, then Int_yy_init_buffer was _probably_
     * called from Int_yyrestart() or through Int_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->Int_yy_bs_lineno = 1;
        b->Int_yy_bs_column = 0;
    }

        b->Int_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Int_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->Int_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->Int_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->Int_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->Int_yy_buf_pos = &b->Int_yy_ch_buf[0];

	b->Int_yy_at_bol = 1;
	b->Int_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Int_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Int_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Int_yyensure_buffer_stack();

	/* This block is copied from Int_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(Int_yy_c_buf_p) = (Int_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_pos = (Int_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(Int_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Int_yy_switch_to_buffer. */
	Int_yy_load_buffer_state( );
	(Int_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Int_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Int_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((Int_yy_buffer_stack_top) > 0)
		--(Int_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Int_yy_load_buffer_state( );
		(Int_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Int_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(Int_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(Int_yy_buffer_stack) = (struct Int_yy_buffer_state**)Int_yyalloc
								(num_to_alloc * sizeof(struct Int_yy_buffer_state*)
								);
		if ( ! (Int_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Int_yyensure_buffer_stack()" );
								  
		memset((Int_yy_buffer_stack), 0, num_to_alloc * sizeof(struct Int_yy_buffer_state*));
				
		(Int_yy_buffer_stack_max) = num_to_alloc;
		(Int_yy_buffer_stack_top) = 0;
		return;
	}

	if ((Int_yy_buffer_stack_top) >= ((Int_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (Int_yy_buffer_stack_max) + grow_size;
		(Int_yy_buffer_stack) = (struct Int_yy_buffer_state**)Int_yyrealloc
								((Int_yy_buffer_stack),
								num_to_alloc * sizeof(struct Int_yy_buffer_state*)
								);
		if ( ! (Int_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Int_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((Int_yy_buffer_stack) + (Int_yy_buffer_stack_max), 0, grow_size * sizeof(struct Int_yy_buffer_state*));
		(Int_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE Int_yy_scan_buffer  (char * base, Int_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) Int_yyalloc(sizeof( struct Int_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_scan_buffer()" );

	b->Int_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->Int_yy_buf_pos = b->Int_yy_ch_buf = base;
	b->Int_yy_is_our_buffer = 0;
	b->Int_yy_input_file = 0;
	b->Int_yy_n_chars = b->Int_yy_buf_size;
	b->Int_yy_is_interactive = 0;
	b->Int_yy_at_bol = 1;
	b->Int_yy_fill_buffer = 0;
	b->Int_yy_buffer_status = YY_BUFFER_NEW;

	Int_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Int_yylex() will
 * scan from a @e copy of @a str.
 * @param Int_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Int_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE Int_yy_scan_string (Int_yyconst char * Int_yystr )
{
    
	return Int_yy_scan_bytes(Int_yystr,strlen(Int_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Int_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Int_yy_scan_bytes  (Int_yyconst char * Int_yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	Int_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) Int_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = Int_yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Int_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Int_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->Int_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void Int_yy_fatal_error (Int_yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine Int_yyless() so it works in section 3 code. */

#undef Int_yyless
#define Int_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Int_yytext. */ \
        int Int_yyless_macro_arg = (n); \
        YY_LESS_LINENO(Int_yyless_macro_arg);\
		Int_yytext[Int_yyleng] = (Int_yy_hold_char); \
		(Int_yy_c_buf_p) = Int_yytext + Int_yyless_macro_arg; \
		(Int_yy_hold_char) = *(Int_yy_c_buf_p); \
		*(Int_yy_c_buf_p) = '\0'; \
		Int_yyleng = Int_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Int_yyget_lineno  (void)
{
        
    return Int_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *Int_yyget_in  (void)
{
        return Int_yyin;
}

/** Get the output stream.
 * 
 */
FILE *Int_yyget_out  (void)
{
        return Int_yyout;
}

/** Get the length of the current token.
 * 
 */
int Int_yyget_leng  (void)
{
        return Int_yyleng;
}

/** Get the current token.
 * 
 */

char *Int_yyget_text  (void)
{
        return Int_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void Int_yyset_lineno (int  line_number )
{
    
    Int_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see Int_yy_switch_to_buffer
 */
void Int_yyset_in (FILE *  in_str )
{
        Int_yyin = in_str ;
}

void Int_yyset_out (FILE *  out_str )
{
        Int_yyout = out_str ;
}

int Int_yyget_debug  (void)
{
        return Int_yy_flex_debug;
}

void Int_yyset_debug (int  bdebug )
{
        Int_yy_flex_debug = bdebug ;
}

static int Int_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Int_yylex_destroy(), so don't allocate here.
     */

    (Int_yy_buffer_stack) = 0;
    (Int_yy_buffer_stack_top) = 0;
    (Int_yy_buffer_stack_max) = 0;
    (Int_yy_c_buf_p) = (char *) 0;
    (Int_yy_init) = 0;
    (Int_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Int_yyin = stdin;
    Int_yyout = stdout;
#else
    Int_yyin = (FILE *) 0;
    Int_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Int_yylex_init()
     */
    return 0;
}

/* Int_yylex_destroy is for both reentrant and non-reentrant scanners. */
int Int_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Int_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Int_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	Int_yyfree((Int_yy_buffer_stack) );
	(Int_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Int_yylex() is called, initialization will occur. */
    Int_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef Int_yytext_ptr
static void Int_yy_flex_strncpy (char* s1, Int_yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int Int_yy_flex_strlen (Int_yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Int_yyalloc (Int_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *Int_yyrealloc  (void * ptr, Int_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void Int_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see Int_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "Int_yytables"

#line 137 "bootscanner.l"



int
Int_yywrap(void)
{
	return 1;
}

void
Int_yyerror(const char *str)
{
	fprintf(stderr,"\tsyntax error %d : %s",GetParserInfo()->Int_yyline, str);
}

