/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class driver_weaver_BaseWeaverConnection_Statement */

#ifndef _Included_driver_weaver_BaseWeaverConnection_Statement
#define _Included_driver_weaver_BaseWeaverConnection_Statement
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
