/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class driver_weaver_BaseWeaverConnection_StreamingType */

#ifndef _Included_driver_weaver_BaseWeaverConnection_StreamingType
#define _Included_driver_weaver_BaseWeaverConnection_StreamingType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
