/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class driver_weaver_WeaverInitializer */

#ifndef _Included_driver_weaver_WeaverInitializer
#define _Included_driver_weaver_WeaverInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     driver_weaver_WeaverInitializer
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverInitializer_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     driver_weaver_WeaverInitializer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverInitializer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
