/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class driver_weaver_BaseWeaverConnection */

#ifndef _Included_driver_weaver_BaseWeaverConnection
#define _Included_driver_weaver_BaseWeaverConnection
#ifdef __cplusplus
extern "C" {
#endif
#undef driver_weaver_BaseWeaverConnection_bindString
#define driver_weaver_BaseWeaverConnection_bindString 2L
#undef driver_weaver_BaseWeaverConnection_bindDouble
#define driver_weaver_BaseWeaverConnection_bindDouble 3L
#undef driver_weaver_BaseWeaverConnection_bindInteger
#define driver_weaver_BaseWeaverConnection_bindInteger 1L
#undef driver_weaver_BaseWeaverConnection_bindBinary
#define driver_weaver_BaseWeaverConnection_bindBinary 6L
#undef driver_weaver_BaseWeaverConnection_bindBLOB
#define driver_weaver_BaseWeaverConnection_bindBLOB 7L
#undef driver_weaver_BaseWeaverConnection_bindCharacter
#define driver_weaver_BaseWeaverConnection_bindCharacter 4L
#undef driver_weaver_BaseWeaverConnection_bindBoolean
#define driver_weaver_BaseWeaverConnection_bindBoolean 5L
#undef driver_weaver_BaseWeaverConnection_bindDate
#define driver_weaver_BaseWeaverConnection_bindDate 12L
#undef driver_weaver_BaseWeaverConnection_bindLong
#define driver_weaver_BaseWeaverConnection_bindLong 13L
#undef driver_weaver_BaseWeaverConnection_bindFunction
#define driver_weaver_BaseWeaverConnection_bindFunction 20L
#undef driver_weaver_BaseWeaverConnection_bindSlot
#define driver_weaver_BaseWeaverConnection_bindSlot 30L
#undef driver_weaver_BaseWeaverConnection_bindJava
#define driver_weaver_BaseWeaverConnection_bindJava 40L
#undef driver_weaver_BaseWeaverConnection_bindText
#define driver_weaver_BaseWeaverConnection_bindText 41L
#undef driver_weaver_BaseWeaverConnection_bindStream
#define driver_weaver_BaseWeaverConnection_bindStream 42L
#undef driver_weaver_BaseWeaverConnection_bindDirect
#define driver_weaver_BaseWeaverConnection_bindDirect 43L
#undef driver_weaver_BaseWeaverConnection_bindNull
#define driver_weaver_BaseWeaverConnection_bindNull 0L
/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    grabConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_driver_weaver_BaseWeaverConnection_grabConnection
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    connectSubConnection
 * Signature: (Ldriver/weaver/BaseWeaverConnection;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_connectSubConnection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    disposeConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_disposeConnection
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    parseStatement
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_driver_weaver_BaseWeaverConnection_parseStatement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    executeStatement
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_driver_weaver_BaseWeaverConnection_executeStatement
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    fetchResults
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_driver_weaver_BaseWeaverConnection_fetchResults
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    setInput
 * Signature: (Ljava/lang/String;ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_setInput
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    getOutput
 * Signature: (IILdriver/weaver/BoundOutput;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_getOutput
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    prepareTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_prepareTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    cancelTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_cancelTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    beginTransaction
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_driver_weaver_BaseWeaverConnection_beginTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    commitTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_commitTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    abortTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_abortTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    beginProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_beginProcedure
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    endProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_endProcedure
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    getTransactionId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_driver_weaver_BaseWeaverConnection_getTransactionId
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    getCommandId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_driver_weaver_BaseWeaverConnection_getCommandId
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_BaseWeaverConnection
 * Method:    streamExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_BaseWeaverConnection_streamExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
