/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_weaverdb_base_BaseWeaverConnection */

#ifndef _Included_org_weaverdb_base_BaseWeaverConnection
#define _Included_org_weaverdb_base_BaseWeaverConnection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_weaverdb_base_BaseWeaverConnection_bindString
#define org_weaverdb_base_BaseWeaverConnection_bindString 2L
#undef org_weaverdb_base_BaseWeaverConnection_bindDouble
#define org_weaverdb_base_BaseWeaverConnection_bindDouble 3L
#undef org_weaverdb_base_BaseWeaverConnection_bindFloat
#define org_weaverdb_base_BaseWeaverConnection_bindFloat 9L
#undef org_weaverdb_base_BaseWeaverConnection_bindShort
#define org_weaverdb_base_BaseWeaverConnection_bindShort 8L
#undef org_weaverdb_base_BaseWeaverConnection_bindInteger
#define org_weaverdb_base_BaseWeaverConnection_bindInteger 1L
#undef org_weaverdb_base_BaseWeaverConnection_bindBinary
#define org_weaverdb_base_BaseWeaverConnection_bindBinary 6L
#undef org_weaverdb_base_BaseWeaverConnection_bindBLOB
#define org_weaverdb_base_BaseWeaverConnection_bindBLOB 7L
#undef org_weaverdb_base_BaseWeaverConnection_bindCharacter
#define org_weaverdb_base_BaseWeaverConnection_bindCharacter 4L
#undef org_weaverdb_base_BaseWeaverConnection_bindBoolean
#define org_weaverdb_base_BaseWeaverConnection_bindBoolean 5L
#undef org_weaverdb_base_BaseWeaverConnection_bindDate
#define org_weaverdb_base_BaseWeaverConnection_bindDate 12L
#undef org_weaverdb_base_BaseWeaverConnection_bindLong
#define org_weaverdb_base_BaseWeaverConnection_bindLong 13L
#undef org_weaverdb_base_BaseWeaverConnection_bindFunction
#define org_weaverdb_base_BaseWeaverConnection_bindFunction 20L
#undef org_weaverdb_base_BaseWeaverConnection_bindSlot
#define org_weaverdb_base_BaseWeaverConnection_bindSlot 30L
#undef org_weaverdb_base_BaseWeaverConnection_bindJava
#define org_weaverdb_base_BaseWeaverConnection_bindJava 40L
#undef org_weaverdb_base_BaseWeaverConnection_bindText
#define org_weaverdb_base_BaseWeaverConnection_bindText 41L
#undef org_weaverdb_base_BaseWeaverConnection_bindStream
#define org_weaverdb_base_BaseWeaverConnection_bindStream 42L
#undef org_weaverdb_base_BaseWeaverConnection_bindDirect
#define org_weaverdb_base_BaseWeaverConnection_bindDirect 43L
#undef org_weaverdb_base_BaseWeaverConnection_bindNull
#define org_weaverdb_base_BaseWeaverConnection_bindNull 0L
/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    grabConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_grabConnection
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    connectSubConnection
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_connectSubConnection
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    disposeConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_disposeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    prepareStatement
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_prepareStatement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    executeStatement
 * Signature: (J[Lorg/weaverdb/base/BoundInput;)J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_executeStatement
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    fetchResults
 * Signature: (J[Lorg/weaverdb/base/BoundOutput;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_weaverdb_base_BaseWeaverConnection_fetchResults
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    prepareTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_prepareTransaction
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    cancelTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_cancelTransaction
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    beginTransaction
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_beginTransaction
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    commitTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_commitTransaction
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    abortTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_abortTransaction
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    beginProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_beginProcedure
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    endProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_endProcedure
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    getTransactionId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_getTransactionId
  (JNIEnv *, jobject);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    getCommandId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_weaverdb_base_BaseWeaverConnection_getCommandId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_weaverdb_base_BaseWeaverConnection
 * Method:    streamExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_weaverdb_base_BaseWeaverConnection_streamExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
