/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_weaverdb_WeaverCmdLine */

#ifndef _Included_org_weaverdb_WeaverCmdLine
#define _Included_org_weaverdb_WeaverCmdLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_weaverdb_WeaverCmdLine
 * Method:    cmd
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_weaverdb_WeaverCmdLine_cmd
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
