/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mtpgsql_server_Connection */

#ifndef _Included_org_mtpgsql_server_Connection
#define _Included_org_mtpgsql_server_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mtpgsql_server_Connection
 * Method:    grabConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mtpgsql_server_Connection_grabConnection
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_mtpgsql_server_Connection
 * Method:    streamExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mtpgsql_server_Connection_streamExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
