/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myosyn_drivers_postgres_PostgresFrameConnection */

#ifndef _Included_com_myosyn_drivers_postgres_PostgresFrameConnection
#define _Included_com_myosyn_drivers_postgres_PostgresFrameConnection
#ifdef __cplusplus
extern "C" {
#endif
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindString
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindString 2L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindDouble
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindDouble 3L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindInteger
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindInteger 1L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindBinary
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindBinary 6L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindBLOB
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindBLOB 7L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindCharacter
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindCharacter 4L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindBoolean
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindBoolean 5L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindDate
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindDate 12L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindLong
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindLong 13L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindFunction
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindFunction 20L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindSlot
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindSlot 30L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindJava
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindJava 40L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindText
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindText 41L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindStream
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindStream 42L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindDirect
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindDirect 43L
#undef com_myosyn_drivers_postgres_PostgresFrameConnection_bindNull
#define com_myosyn_drivers_postgres_PostgresFrameConnection_bindNull 0L
/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    openChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_openChannel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    sendToBackend
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_sendToBackend
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    receiveFromBackend
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_receiveFromBackend
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    closeChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_closeChannel
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    grabConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_grabConnection
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    connectSubConnection
 * Signature: (Lcom/myosyn/drivers/postgres/PostgresFrameConnection;)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_connectSubConnection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    begin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_begin
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    parseStatement
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_parseStatement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    bind
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_bind
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    setBind
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_setBind
  (JNIEnv *, jobject, jstring, jobject, jstring, jint);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    outputLink
 * Signature: (IILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_outputLink
  (JNIEnv *, jobject, jint, jint, jobject, jstring, jstring, jstring);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    execute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_execute
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    fetch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_fetch
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    disposeConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_disposeConnection
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    prepare
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_prepare
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    userLock
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_userLock
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_commit
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    rollBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_rollBack
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_cancel
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    getTransactionId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_getTransactionId
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    streamExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_streamExec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    beginProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_beginProcedure
  (JNIEnv *, jobject);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresFrameConnection
 * Method:    endProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresFrameConnection_endProcedure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
