/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myosyn_drivers_postgres_PostgresInitializer */

#ifndef _Included_com_myosyn_drivers_postgres_PostgresInitializer
#define _Included_com_myosyn_drivers_postgres_PostgresInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myosyn_drivers_postgres_PostgresInitializer
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresInitializer_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_myosyn_drivers_postgres_PostgresInitializer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myosyn_drivers_postgres_PostgresInitializer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
