/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mtpgsql_server_SimpleServer */

#ifndef _Included_org_mtpgsql_server_SimpleServer
#define _Included_org_mtpgsql_server_SimpleServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mtpgsql_server_SimpleServer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mtpgsql_server_SimpleServer_init
  (JNIEnv *, jclass);

/*
 * Class:     org_mtpgsql_server_SimpleServer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mtpgsql_server_SimpleServer_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
