%.dylib: %.o
	$(LD) -bundle -o $@ $<
PG_HOME=${SRCDIR}
MK_NO_LORDER=true
CFLAGS+= -traditional-cpp -g -DMACOSX -DNOARRAY
#BKIOPTS+= -traditional-cpp -DNOARRAY
BKIOPTS+= -DNOARRAY
PORTNAME= macosx
AROPTS= cr
LIBS= -lm -lcurses -lpthread
CPU= ppc
LIBPATH=\
-L${PG_HOME} \
-L${PG_HOME}/backend \
-L/usr/lib  
LDFLAGS= $(LIBPATH) $(LIBS)
INSTALL= ${SRCDIR}/install-sh -c
POSTGRESDIR=/usr/local/mtpgsql
