/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class driver_weaver_WeaverFrameConnection */

#ifndef _Included_driver_weaver_WeaverFrameConnection
#define _Included_driver_weaver_WeaverFrameConnection
#ifdef __cplusplus
extern "C" {
#endif
#undef driver_weaver_WeaverFrameConnection_bindString
#define driver_weaver_WeaverFrameConnection_bindString 2L
#undef driver_weaver_WeaverFrameConnection_bindDouble
#define driver_weaver_WeaverFrameConnection_bindDouble 3L
#undef driver_weaver_WeaverFrameConnection_bindInteger
#define driver_weaver_WeaverFrameConnection_bindInteger 1L
#undef driver_weaver_WeaverFrameConnection_bindBinary
#define driver_weaver_WeaverFrameConnection_bindBinary 6L
#undef driver_weaver_WeaverFrameConnection_bindBLOB
#define driver_weaver_WeaverFrameConnection_bindBLOB 7L
#undef driver_weaver_WeaverFrameConnection_bindCharacter
#define driver_weaver_WeaverFrameConnection_bindCharacter 4L
#undef driver_weaver_WeaverFrameConnection_bindBoolean
#define driver_weaver_WeaverFrameConnection_bindBoolean 5L
#undef driver_weaver_WeaverFrameConnection_bindDate
#define driver_weaver_WeaverFrameConnection_bindDate 12L
#undef driver_weaver_WeaverFrameConnection_bindLong
#define driver_weaver_WeaverFrameConnection_bindLong 13L
#undef driver_weaver_WeaverFrameConnection_bindFunction
#define driver_weaver_WeaverFrameConnection_bindFunction 20L
#undef driver_weaver_WeaverFrameConnection_bindSlot
#define driver_weaver_WeaverFrameConnection_bindSlot 30L
#undef driver_weaver_WeaverFrameConnection_bindJava
#define driver_weaver_WeaverFrameConnection_bindJava 40L
#undef driver_weaver_WeaverFrameConnection_bindText
#define driver_weaver_WeaverFrameConnection_bindText 41L
#undef driver_weaver_WeaverFrameConnection_bindStream
#define driver_weaver_WeaverFrameConnection_bindStream 42L
#undef driver_weaver_WeaverFrameConnection_bindDirect
#define driver_weaver_WeaverFrameConnection_bindDirect 43L
#undef driver_weaver_WeaverFrameConnection_bindNull
#define driver_weaver_WeaverFrameConnection_bindNull 0L
/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    grabConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_grabConnection
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    connectSubConnection
 * Signature: (Ldriver/weaver/WeaverFrameConnection;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_connectSubConnection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    parseStatement
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_parseStatement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    bind
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_bind
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    setBind
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_setBind
  (JNIEnv *, jobject, jstring, jobject, jstring, jint);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    outputLink
 * Signature: (IILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_outputLink
  (JNIEnv *, jobject, jint, jint, jobject, jstring, jstring, jstring);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    execute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_execute
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    fetch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_fetch
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    disposeConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_disposeConnection
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    prepare
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_prepare
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    userLock
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_userLock
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    beginTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_beginTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    commitTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_commitTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    abortTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_abortTransaction
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    beginProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_beginProcedure
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    endProcedure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_endProcedure
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    getTransactionId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_driver_weaver_WeaverFrameConnection_getTransactionId
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_cancel
  (JNIEnv *, jobject);

/*
 * Class:     driver_weaver_WeaverFrameConnection
 * Method:    streamExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_driver_weaver_WeaverFrameConnection_streamExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
