/*-------------------------------------------------------------------------
 *
 * fmgr.h--
 *    Definitions for using internal procedures.
 *
 *
 * Copyright (c) 1994, Regents of the University of California
 *
 * : Gen_fmgrtab.sh,v 1.1.1.1 2006/08/12 00:21:34 synmscott Exp $
 *
 * NOTES
 *	******************************
 *	*** DO NOT EDIT THIS FILE! ***
 *	******************************
 *
 *	It has been GENERATED by Gen_fmgrtab.sh
 *	from ../../include/catalog/pg_proc.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef	FMGR_H
#define FMGR_H

typedef struct {
    Datum data[FUNC_MAX_ARGS];
} FmgrValues;

typedef struct {
    func_ptr	fn_addr;
    Oid		fn_oid;
    void*       fn_data;
    int		fn_nargs;
} FmgrInfo;

/*
 * defined in fmgr.c
 */
#ifdef __cplusplus
extern "C" {
#endif

extern char *fmgr_c(FmgrInfo *finfo, FmgrValues *values, bool *isNull);
extern Oid fmgr_info(Oid procedureId, FmgrInfo *finfo);
extern char *fmgr(Oid procedureId,... );
extern char *fmgr_ptr(FmgrInfo *finfo, ... );
extern char *fmgr_array_args(Oid procedureId, int nargs, 
			     char *args[], bool *isNull);

#ifdef __cplusplus
}
#endif

/*
 * defined in dfmgr.c
 */
/*  we are removing dynamic load for now b/c it does not work with java  MKS 11.23.2001  

extern func_ptr fmgr_dynamic(Oid procedureId, int *pronargs);
extern void load_file(char *filename);
*/
/*
 *	For performance reasons, we often want to simply jump through a
 *	a function pointer (if it's valid, that is).  These calls have
 *	been macroized so we can run them through a routine that does
 *	sanity-checking (and so we can track them down more easily when
 *	we must).
 */

/* We don't make this static so fmgr_faddr() macros can access it */
/*
extern FmgrInfo        *fmgr_pl_finfo;
*/

#ifdef NOTUSED
#define fmgr_faddr(finfo) ( 	fmgr_pl_finfo = (finfo), 	(func_ptr)(finfo)->fn_addr )
#endif
#define fmgr_faddr(finfo) ( (func_ptr)(finfo)->fn_addr )
#define fmgr_faddr_1(finfo) ( (func_ptr_1)(finfo)->fn_addr )
#define fmgr_faddr_2(finfo) ( (func_ptr_2)(finfo)->fn_addr )
#define fmgr_faddr_3(finfo) ( (func_ptr_3)(finfo)->fn_addr )
#define fmgr_faddr_4(finfo) ( (func_ptr_4)(finfo)->fn_addr )
#define fmgr_faddr_5(finfo) ( (func_ptr_5)(finfo)->fn_addr )
#define fmgr_faddr_6(finfo) ( (func_ptr_6)(finfo)->fn_addr )
#define fmgr_faddr_7(finfo) ( (func_ptr_7)(finfo)->fn_addr )
#define fmgr_faddr_8(finfo) ( (func_ptr_8)(finfo)->fn_addr )
#define fmgr_faddr_9(finfo) ( (func_ptr_9)(finfo)->fn_addr )
#ifdef TRACE_FMGR_PTR
#define	FMGR_PTR2(FINFO, ARG1, ARG2) 	fmgr_ptr(FINFO, ARG1, ARG2)
#else
#define	FMGR_PTR2(FINFO, ARG1, ARG2) ( 	((FINFO)->fn_addr) ? 		(*(fmgr_faddr_2(FINFO)))(ARG1, ARG2) 	: 		fmgr((FINFO)->fn_oid, ARG1, ARG2) )
#endif

/*
 *	Flags for the builtin oprrest selectivity routines.
 */
#define	SEL_CONSTANT 	1	/* constant does not vary (not a parameter) */
#define	SEL_RIGHT	2 	/* constant appears to right of operator */

/*
 *	Constant macros for the OIDs of entries in pg_proc.
 *	NOTE: if the same "proname" is used for more than one
 *	internal-function entry in pg_proc, the equivalent macro
 *	will be defined with the lowest OID among those entries.
 */
#define F_UPDATE_PG_PWD 12
#define F_BYTEAOUT 31
#define F_CHAROUT 33
#define F_NAMEIN 34
#define F_NAMEOUT 35
#define F_INT2IN 38
#define F_INT2OUT 39
#define F_INT2VECTORIN 40
#define F_INT2VECTOROUT 41
#define F_INT4IN 42
#define F_INT4OUT 43
#define F_REGPROCIN 44
#define F_REGPROCOUT 45
#define F_TEXTIN 46
#define F_TEXTOUT 47
#define F_TIDIN 48
#define F_TIDOUT 49
#define F_XIDIN 50
#define F_XIDOUT 51
#define F_CIDIN 52
#define F_CIDOUT 53
#define F_OIDVECTORIN 54
#define F_OIDVECTOROUT 55
#define F_BOOLLT 56
#define F_BOOLGT 57
#define F_BOOLEQ 60
#define F_CHAREQ 61
#define F_NAMEEQ 62
#define F_INT2EQ 63
#define F_INT2LT 64
#define F_INT4EQ 65
#define F_INT4LT 66
#define F_TEXTEQ 67
#define F_XIDEQ 68
#define F_CIDEQ 69
#define F_CHARNE 70
#define F_CHARLE 72
#define F_CHARGT 73
#define F_CHARGE 74
#define F_CHARMUL 77
#define F_CHARDIV 78
#define F_NAMEREGEXEQ 79
#define F_BOOLNE 84
#define F_VERSION 89
#define F_INT8FAC 100
#define F_EQSEL 101
#define F_NEQSEL 102
#define F_SCALARLTSEL 103
#define F_SCALARGTSEL 104
#define F_EQJOINSEL 105
#define F_NEQJOINSEL 106
#define F_SCALARLTJOINSEL 107
#define F_SCALARGTJOINSEL 108
#define F_TEXT 112
#define F_INT4MUL 141
#define F_INT4FAC 142
#define F_INT4NE 144
#define F_INT2NE 145
#define F_INT2GT 146
#define F_INT4GT 147
#define F_INT2LE 148
#define F_INT4LE 149
#define F_INT4GE 150
#define F_INT2GE 151
#define F_INT2MUL 152
#define F_INT2DIV 153
#define F_INT4DIV 154
#define F_INT2MOD 155
#define F_INT4MOD 156
#define F_TEXTNE 157
#define F_INT24EQ 158
#define F_INT42EQ 159
#define F_INT24LT 160
#define F_INT42LT 161
#define F_INT24GT 162
#define F_INT42GT 163
#define F_INT24NE 164
#define F_INT42NE 165
#define F_INT24LE 166
#define F_INT42LE 167
#define F_INT24GE 168
#define F_INT42GE 169
#define F_INT24MUL 170
#define F_INT42MUL 171
#define F_INT24DIV 172
#define F_INT42DIV 173
#define F_INT24MOD 174
#define F_INT42MOD 175
#define F_INT2PL 176
#define F_INT4PL 177
#define F_INT24PL 178
#define F_INT42PL 179
#define F_INT2MI 180
#define F_INT4MI 181
#define F_INT24MI 182
#define F_INT42MI 183
#define F_OIDEQ 184
#define F_OIDNE 185
#define F_FLOAT4IN 200
#define F_FLOAT4OUT 201
#define F_FLOAT4MUL 202
#define F_FLOAT4DIV 203
#define F_FLOAT4PL 204
#define F_FLOAT4MI 205
#define F_FLOAT4UM 206
#define F_FLOAT4ABS 207
#define F_FLOAT4INC 208
#define F_FLOAT4LARGER 209
#define F_FLOAT4SMALLER 211
#define F_INT4UM 212
#define F_INT2UM 213
#define F_FLOAT8IN 214
#define F_FLOAT8OUT 215
#define F_FLOAT8MUL 216
#define F_FLOAT8DIV 217
#define F_FLOAT8PL 218
#define F_FLOAT8MI 219
#define F_FLOAT8UM 220
#define F_FLOAT8ABS 221
#define F_FLOAT8INC 222
#define F_FLOAT8LARGER 223
#define F_FLOAT8SMALLER 224
#define F_DROUND 228
#define F_DTRUNC 229
#define F_DSQRT 230
#define F_DCBRT 231
#define F_DPOW 232
#define F_DEXP 233
#define F_DLOG1 234
#define F_FLOAT8 235
#define F_FLOAT4 236
#define F_INT2 237
#define F_NABSTIMEIN 240
#define F_NABSTIMEOUT 241
#define F_RELTIMEIN 242
#define F_RELTIMEOUT 243
#define F_TIMEPL 244
#define F_TIMEMI 245
#define F_TINTERVALIN 246
#define F_TINTERVALOUT 247
#define F_INTINTERVAL 248
#define F_TINTERVALREL 249
#define F_TIMENOW 250
#define F_ABSTIMEEQ 251
#define F_ABSTIMENE 252
#define F_ABSTIMELT 253
#define F_ABSTIMEGT 254
#define F_ABSTIMELE 255
#define F_ABSTIMEGE 256
#define F_RELTIMEEQ 257
#define F_RELTIMENE 258
#define F_RELTIMELT 259
#define F_RELTIMEGT 260
#define F_RELTIMELE 261
#define F_RELTIMEGE 262
#define F_TINTERVALSAME 263
#define F_TINTERVALCT 264
#define F_TINTERVALOV 265
#define F_TINTERVALLENEQ 266
#define F_TINTERVALLENNE 267
#define F_TINTERVALLENLT 268
#define F_TINTERVALLENGT 269
#define F_TINTERVALLENLE 270
#define F_TINTERVALLENGE 271
#define F_TINTERVALSTART 272
#define F_TINTERVALEND 273
#define F_TIMEOFDAY 274
#define F_ISFINITE 275
#define F_INT2FAC 276
#define F_FLOAT48MUL 279
#define F_FLOAT48DIV 280
#define F_FLOAT48PL 281
#define F_FLOAT48MI 282
#define F_FLOAT84MUL 283
#define F_FLOAT84DIV 284
#define F_FLOAT84PL 285
#define F_FLOAT84MI 286
#define F_FLOAT4EQ 287
#define F_FLOAT4NE 288
#define F_FLOAT4LT 289
#define F_FLOAT4LE 290
#define F_FLOAT4GT 291
#define F_FLOAT4GE 292
#define F_FLOAT8EQ 293
#define F_FLOAT8NE 294
#define F_FLOAT8LT 295
#define F_FLOAT8LE 296
#define F_FLOAT8GT 297
#define F_FLOAT8GE 298
#define F_FLOAT48EQ 299
#define F_FLOAT48NE 300
#define F_FLOAT48LT 301
#define F_FLOAT48LE 302
#define F_FLOAT48GT 303
#define F_FLOAT48GE 304
#define F_FLOAT84EQ 305
#define F_FLOAT84NE 306
#define F_FLOAT84LT 307
#define F_FLOAT84LE 308
#define F_FLOAT84GT 309
#define F_FLOAT84GE 310
#define F_INT4 313
#define F_INT2VECTOREQ 315
#define F_BTGETTUPLE 330
#define F_BTINSERT 331
#define F_BTBULKDELETE 332
#define F_BTBEGINSCAN 333
#define F_BTRESCAN 334
#define F_BTENDSCAN 335
#define F_BTMARKPOS 336
#define F_BTRESTRPOS 337
#define F_BTBUILD 338
#define F_BTINT2CMP 350
#define F_BTINT4CMP 351
#define F_BTINT42CMP 352
#define F_BTINT24CMP 353
#define F_BTFLOAT4CMP 354
#define F_BTFLOAT8CMP 355
#define F_BTOIDCMP 356
#define F_BTABSTIMECMP 357
#define F_BTCHARCMP 358
#define F_BTNAMECMP 359
#define F_BTTEXTCMP 360
#define F_MD5 402
#define F_BTOIDVECTORCMP 404
#define F_NAME 407
#define F_BPCHAR 408
#define F_MACADDR_IN 436
#define F_MACADDR_OUT 437
#define F_HASHCOSTESTIMATE 438
#define F_HASHGETTUPLE 440
#define F_HASHINSERT 441
#define F_HASHDELETE 442
#define F_HASHBEGINSCAN 443
#define F_HASHRESCAN 444
#define F_HASHENDSCAN 445
#define F_HASHMARKPOS 446
#define F_HASHRESTRPOS 447
#define F_HASHBUILD 448
#define F_HASHINT2 449
#define F_HASHINT4 450
#define F_HASHFLOAT4 451
#define F_HASHFLOAT8 452
#define F_HASHOID 453
#define F_HASHCHAR 454
#define F_HASHNAME 455
#define F_HASHTEXT 456
#define F_HASHOIDVECTOR 457
#define F_TEXT_LARGER 458
#define F_TEXT_SMALLER 459
#define F_INT8IN 460
#define F_INT8OUT 461
#define F_INT8UM 462
#define F_INT8PL 463
#define F_INT8MI 464
#define F_INT8MUL 465
#define F_INT8DIV 466
#define F_INT8EQ 467
#define F_INT8NE 468
#define F_INT8LT 469
#define F_INT8GT 470
#define F_INT8LE 471
#define F_INT8GE 472
#define F_INT84EQ 474
#define F_INT84NE 475
#define F_INT84LT 476
#define F_INT84GT 477
#define F_INT84LE 478
#define F_INT84GE 479
#define F_INT8 481
#define F_OIDVECTORNE 619
#define F_INT44OUT 653
#define F_NAMELT 655
#define F_NAMELE 656
#define F_NAMEGT 657
#define F_NAMEGE 658
#define F_NAMENE 659
#define F_VARCHAR 669
#define F_MKTINTERVAL 676
#define F_OIDVECTORLT 677
#define F_OIDVECTORLE 678
#define F_OIDVECTOREQ 679
#define F_OIDVECTORGE 680
#define F_OIDVECTORGT 681
#define F_NETWORK 683
#define F_NETMASK 696
#define F_MASKLEN 697
#define F_BROADCAST 698
#define F_HOST 699
#define F_GETPGUSERNAME 710
#define F_USERFNTEST 711
#define F_OIDRAND 713
#define F_OIDSRAND 715
#define F_OIDEQINT4 716
#define F_INT4EQOID 717
#define F_OCTET_LENGTH 720
#define F_GET_BYTE 721
#define F_SET_BYTE 722
#define F_GET_BIT 723
#define F_SET_BIT 724
#define F_PQTEST 730
#define F_TEXT_LT 740
#define F_TEXT_LE 741
#define F_TEXT_GT 742
#define F_TEXT_GE 743
#define F_FILENAME_IN 752
#define F_FILENAME_OUT 753
#define F_SMGRIN 760
#define F_SMGROUT 761
#define F_SMGREQ 762
#define F_SMGRNE 763
#define F_OIDIN 764
#define F_OIDOUT 765
#define F_INT4INC 766
#define F_INT2INC 767
#define F_INT4LARGER 768
#define F_INT4SMALLER 769
#define F_INT2LARGER 770
#define F_INT2SMALLER 771
#define F_TINTERVALEQ 784
#define F_TINTERVALNE 785
#define F_TINTERVALLT 786
#define F_TINTERVALGT 787
#define F_TINTERVALLE 788
#define F_TINTERVALGE 789
#define F_OID 817
#define F_MACADDR_EQ 830
#define F_MACADDR_LT 831
#define F_MACADDR_LE 832
#define F_MACADDR_GT 833
#define F_MACADDR_GE 834
#define F_MACADDR_NE 835
#define F_MACADDR_CMP 836
#define F_MACADDR_MANUF 837
#define F_BTINT8CMP 842
#define F_CASH_MUL_FLT4 846
#define F_CASH_DIV_FLT4 847
#define F_FLT4_MUL_CASH 848
#define F_POSITION 849
#define F_TEXTLIKE 850
#define F_TEXTNLIKE 851
#define F_INT48EQ 852
#define F_INT48NE 853
#define F_INT48LT 854
#define F_INT48GT 855
#define F_INT48LE 856
#define F_INT48GE 857
#define F_NAMELIKE 858
#define F_NAMENLIKE 859
#define F_CHAR 861
#define F_INT4_MUL_CASH 862
#define F_INT2_MUL_CASH 863
#define F_CASH_MUL_INT4 864
#define F_CASH_DIV_INT4 865
#define F_CASH_MUL_INT2 866
#define F_CASH_DIV_INT2 867
#define F_CASH_IN 886
#define F_CASH_OUT 887
#define F_CASH_EQ 888
#define F_CASH_NE 889
#define F_CASH_LT 890
#define F_CASH_LE 891
#define F_CASH_GT 892
#define F_CASH_GE 893
#define F_CASH_PL 894
#define F_CASH_MI 895
#define F_CASH_MUL_FLT8 896
#define F_CASH_DIV_FLT8 897
#define F_CASHLARGER 898
#define F_CASHSMALLER 899
#define F_INET_IN 910
#define F_INET_OUT 911
#define F_FLT8_MUL_CASH 919
#define F_NETWORK_EQ 920
#define F_NETWORK_LT 921
#define F_NETWORK_LE 922
#define F_NETWORK_GT 923
#define F_NETWORK_GE 924
#define F_NETWORK_NE 925
#define F_NETWORK_CMP 926
#define F_NETWORK_SUB 927
#define F_NETWORK_SUBEQ 928
#define F_NETWORK_SUP 929
#define F_NETWORK_SUPEQ 930
#define F_MOD 940
#define F_INT8MOD 945
#define F_HASHINT8 949
#define F_ISTRUE 950
#define F_ISFALSE 951
#define F_LONGIN 953
#define F_LONGOUT 954
#define F_LONGEQOID 955
#define F_OIDEQLONG 956
#define F_REGPROCTOOID 972
#define F_NULLVALUE 1029
#define F_NONNULLVALUE 1030
#define F_SETEVAL 1038
#define F_GETDATABASEENCODING 1039
#define F_BPCHARIN 1044
#define F_BPCHAROUT 1045
#define F_VARCHARIN 1046
#define F_VARCHAROUT 1047
#define F_BPCHAREQ 1048
#define F_BPCHARLT 1049
#define F_BPCHARLE 1050
#define F_BPCHARGT 1051
#define F_BPCHARGE 1052
#define F_BPCHARNE 1053
#define F_VARCHAREQ 1070
#define F_VARCHARLT 1071
#define F_VARCHARLE 1072
#define F_VARCHARGT 1073
#define F_VARCHARGE 1074
#define F_VARCHARNE 1075
#define F_BPCHARCMP 1078
#define F_VARCHARCMP 1079
#define F_HASHBPCHAR 1080
#define F_HASHVARCHAR 1081
#define F_DATE_IN 1084
#define F_DATE_OUT 1085
#define F_DATE_EQ 1086
#define F_DATE_LT 1087
#define F_DATE_LE 1088
#define F_DATE_GT 1089
#define F_DATE_GE 1090
#define F_DATE_NE 1091
#define F_DATE_CMP 1092
#define F_TIME_LT 1102
#define F_TIME_LE 1103
#define F_TIME_GT 1104
#define F_TIME_GE 1105
#define F_TIME_NE 1106
#define F_TIME_CMP 1107
#define F_BTCONNECTORCMP 1137
#define F_DATE_LARGER 1138
#define F_DATE_SMALLER 1139
#define F_DATE_MI 1140
#define F_DATE_PLI 1141
#define F_DATE_MII 1142
#define F_TIME_IN 1143
#define F_TIME_OUT 1144
#define F_TIME_EQ 1145
#define F_TIMESTAMP_IN 1150
#define F_TIMESTAMP_OUT 1151
#define F_TIMESTAMP_EQ 1152
#define F_TIMESTAMP_NE 1153
#define F_TIMESTAMP_LT 1154
#define F_TIMESTAMP_LE 1155
#define F_TIMESTAMP_GE 1156
#define F_TIMESTAMP_GT 1157
#define F_TIMEZONE 1159
#define F_INTERVAL_IN 1160
#define F_INTERVAL_OUT 1161
#define F_INTERVAL_EQ 1162
#define F_INTERVAL_NE 1163
#define F_INTERVAL_LT 1164
#define F_INTERVAL_LE 1165
#define F_INTERVAL_GE 1166
#define F_INTERVAL_GT 1167
#define F_INTERVAL_UM 1168
#define F_INTERVAL_PL 1169
#define F_INTERVAL_MI 1170
#define F_DATE_PART 1171
#define F_TIMESTAMP 1173
#define F_INTERVAL 1177
#define F_DATE 1178
#define F_ABSTIME 1180
#define F_TIMESTAMP_MI 1188
#define F_TIMESTAMP_PL_SPAN 1189
#define F_TIMESTAMP_MI_SPAN 1190
#define F_RELTIME 1194
#define F_TIMESTAMP_SMALLER 1195
#define F_TIMESTAMP_LARGER 1196
#define F_INTERVAL_SMALLER 1197
#define F_INTERVAL_LARGER 1198
#define F_AGE 1199
#define F_DATE_TRUNC 1217
#define F_INT8ABS 1230
#define F_INT8LARGER 1236
#define F_INT8SMALLER 1237
#define F_TEXTICREGEXEQ 1238
#define F_TEXTICREGEXNE 1239
#define F_NAMEICREGEXEQ 1240
#define F_NAMEICREGEXNE 1241
#define F_BOOLIN 1242
#define F_BOOLOUT 1243
#define F_BYTEAIN 1244
#define F_CHARIN 1245
#define F_CHARLT 1246
#define F_CHARPL 1248
#define F_CHARMI 1250
#define F_INT4ABS 1251
#define F_NAMEREGEXNE 1252
#define F_INT2ABS 1253
#define F_TEXTREGEXEQ 1254
#define F_TEXTREGEXNE 1256
#define F_TEXTLEN 1257
#define F_TEXTCAT 1258
#define F_CIDR_IN 1267
#define F_BTCOSTESTIMATE 1268
#define F_OVERLAPS 1271
#define F_DATETIME_PL 1272
#define F_CASH_WORDS_OUT 1273
#define F_INT84PL 1274
#define F_INT84MI 1275
#define F_INT84MUL 1276
#define F_INT84DIV 1277
#define F_INT48PL 1278
#define F_INT48MI 1279
#define F_INT48MUL 1280
#define F_INT48DIV 1281
#define F_INT4NOTIN 1285
#define F_OIDNOTIN 1286
#define F_INT44IN 1287
#define F__BPCHAR 1290
#define F__VARCHAR 1291
#define F_TIDEQ 1292
#define F_CURRTID 1293
#define F_CURRTID2 1294
#define F_PG_CHAR_TO_ENCODING 1295
#define F_DATETIMETZ_PL 1297
#define F_NOW 1299
#define F_TIMESTAMP_CMP 1314
#define F_INTERVAL_CMP 1315
#define F_TIME 1316
#define F_LENGTH 1317
#define F_INTERVAL_DIV 1326
#define F_DLOG10 1339
#define F_LOG 1340
#define F_LN 1341
#define F_ROUND 1342
#define F_TRUNC 1343
#define F_SQRT 1344
#define F_CBRT 1345
#define F_POW 1346
#define F_EXP 1347
#define F_OIDVECTORTYPES 1349
#define F_TIMETZ_IN 1350
#define F_TIMETZ_OUT 1351
#define F_TIMETZ_EQ 1352
#define F_TIMETZ_NE 1353
#define F_TIMETZ_LT 1354
#define F_TIMETZ_LE 1355
#define F_TIMETZ_GE 1356
#define F_TIMETZ_GT 1357
#define F_TIMETZ_CMP 1358
#define F_CHAR_LENGTH 1372
#define F_TIME_LARGER 1377
#define F_TIME_SMALLER 1378
#define F_TIMETZ_LARGER 1379
#define F_TIMETZ_SMALLER 1380
#define F_TIMETZ 1388
#define F_FACTORIAL 1391
#define F_ABS 1394
#define F_CIDR_OUT 1427
#define F_BYTEAEQ 1506
#define F_BYTEALT 1507
#define F_BYTEALE 1508
#define F_BYTEAGT 1509
#define F_BYTEAGE 1510
#define F_BYTEANE 1511
#define F_BYTEACMP 1512
#define F_TID 1513
#define F_BYTEA 1514
#define F_SHA2 1519
#define F_ZPBIT_IN 1564
#define F_ZPBIT_OUT 1565
#define F_LIKE 1569
#define F_NOTLIKE 1570
#define F_NEXTVAL 1574
#define F_CURRVAL 1575
#define F_SETVAL 1576
#define F_VARBIT_IN 1579
#define F_VARBIT_OUT 1580
#define F_BITEQ 1581
#define F_BITNE 1582
#define F_BITGE 1592
#define F_BITGT 1593
#define F_BITLE 1594
#define F_BITLT 1595
#define F_BITCMP 1596
#define F_PG_ENCODING_TO_CHAR 1597
#define F_RANDOM 1598
#define F_SETSEED 1599
#define F_ASIN 1600
#define F_ACOS 1601
#define F_ATAN 1602
#define F_ATAN2 1603
#define F_SIN 1604
#define F_COS 1605
#define F_TAN 1606
#define F_COT 1607
#define F_DEGREES 1608
#define F_RADIANS 1609
#define F_PI 1610
#define F_INTERVAL_MUL 1618
#define F_MUL_D_INTERVAL 1624
#define F_LZTEXTIN 1626
#define F_LZTEXTOUT 1627
#define F_LZTEXT 1631
#define F_LZTEXT_CMP 1636
#define F_LZTEXT_EQ 1637
#define F_LZTEXT_NE 1638
#define F_LZTEXT_GT 1639
#define F_PG_GET_RULEDEF 1640
#define F_PG_GET_VIEWDEF 1641
#define F_PG_GET_USERBYID 1642
#define F_PG_GET_INDEXDEF 1643
#define F_RI_FKEY_CHECK_INS 1644
#define F_RI_FKEY_CHECK_UPD 1645
#define F_RI_FKEY_CASCADE_DEL 1646
#define F_RI_FKEY_CASCADE_UPD 1647
#define F_RI_FKEY_RESTRICT_DEL 1648
#define F_RI_FKEY_RESTRICT_UPD 1649
#define F_RI_FKEY_SETNULL_DEL 1650
#define F_RI_FKEY_SETNULL_UPD 1651
#define F_RI_FKEY_SETDEFAULT_DEL 1652
#define F_RI_FKEY_SETDEFAULT_UPD 1653
#define F_RI_FKEY_NOACTION_DEL 1654
#define F_RI_FKEY_NOACTION_UPD 1655
#define F_LZTEXT_LE 1656
#define F_LZTEXT_GE 1664
#define F_LZTEXT_LT 1665
#define F_VARBITEQ 1666
#define F_VARBITNE 1667
#define F_VARBITGE 1668
#define F_VARBITGT 1669
#define F_VARBITLE 1670
#define F_VARBITLT 1671
#define F_VARBITCMP 1672
#define F_BITAND 1673
#define F_BITOR 1674
#define F_BITXOR 1675
#define F_BITNOT 1676
#define F_BITSHIFTRIGHT 1677
#define F_BITSHIFTLEFT 1678
#define F_BITCAT 1679
#define F_BITSUBSTR 1680
#define F_VARBITAND 1681
#define F_VARBITOR 1682
#define F_VARBITXOR 1683
#define F_VARBITNOT 1684
#define F_VARBITSHIFTRIGHT 1685
#define F_VARBITSHIFTLEFT 1686
#define F_VARBITCAT 1687
#define F_VARBITSUBSTR 1688
#define F_BOOLLE 1691
#define F_BOOLGE 1692
#define F_BTBOOLCMP 1693
#define F_NUMERIC_IN 1701
#define F_NUMERIC_OUT 1702
#define F_NUMERIC 1703
#define F_NUMERIC_ABS 1704
#define F_SIGN 1706
#define F_CEIL 1711
#define F_FLOOR 1712
#define F_NUMERIC_EQ 1718
#define F_NUMERIC_NE 1719
#define F_NUMERIC_GT 1720
#define F_NUMERIC_GE 1721
#define F_NUMERIC_LT 1722
#define F_NUMERIC_LE 1723
#define F_NUMERIC_ADD 1724
#define F_NUMERIC_SUB 1725
#define F_NUMERIC_MUL 1726
#define F_NUMERIC_DIV 1727
#define F_NUMERIC_MOD 1729
#define F_NUMERIC_SQRT 1731
#define F_NUMERIC_EXP 1733
#define F_NUMERIC_LN 1735
#define F_NUMERIC_LOG 1737
#define F_NUMERIC_POWER 1739
#define F_NUMERIC_INC 1764
#define F_NUMERIC_DEC 1765
#define F_NUMERIC_SMALLER 1766
#define F_NUMERIC_LARGER 1767
#define F_NUMERIC_CMP 1769
#define F_TO_CHAR 1770
#define F_NUMERIC_UMINUS 1771
#define F_TO_NUMBER 1777
#define F_TO_TIMESTAMP 1778
#define F_TO_DATE 1780
#define F_CONNECTORTOINT4 1801
#define F_INT4TOCONNECTOR 1802
#define F_REGEXEQSEL 1818
#define F_LIKESEL 1819
#define F_ICREGEXEQSEL 1820
#define F_REGEXNESEL 1821
#define F_NLIKESEL 1822
#define F_ICREGEXNESEL 1823
#define F_REGEXEQJOINSEL 1824
#define F_LIKEJOINSEL 1825
#define F_ICREGEXEQJOINSEL 1826
#define F_REGEXNEJOINSEL 1827
#define F_NLIKEJOINSEL 1828
#define F_ICREGEXNEJOINSEL 1829
#define F_JAVAIN 1831
#define F_JAVAOUT 1832
#define F_WRAPPEDIN 1838
#define F_WRAPPEDOUT 1839
#define F_WRAPPEDTOTEXT 1840
#define F_BTRECOVERPAGE 1842
#define F_JAVA_INSTANCEOF 1999
#define F_JAVA_COMPARE 2010
#define F_JAVA_EQUALS 2011
#define F_JAVA_LT 2012
#define F_JAVA_GT 2013
#define F_JAVA_LTEQ 2014
#define F_JAVA_GTEQ 2015
#define F_JAVATEXTIN 2016
#define F_JAVATEXTOUT 2017
#define F_JAVA_NOTEQ 2018
#define F_XIDINT8_EQUALS 2111
#define F_XIDINT8_LT 2112
#define F_XIDINT8_GT 2113
#define F_XIDINT8_LTEQ 2114
#define F_XIDINT8_GTEQ 2115
#define F_XIDINT8_NOTEQ 2118
#define F_XIDINT4_EQUALS 2211
#define F_XIDINT4_LT 2212
#define F_XIDINT4_GT 2213
#define F_XIDINT4_LTEQ 2214
#define F_XIDINT4_GTEQ 2215
#define F_XIDINT4_NOTEQ 2218

#endif	/* FMGR_H */
